language: go
go: '1.9'

services:
  - docker

jobs:
  include:
    - stage: install depeendencies
      script: ./install-dependencies.sh

    - stage: build
      script: go build -o $GOPATH/src/github.com/AwesomeTeamPlayer/users-service-go/app github.com/AwesomeTeamPlayer/users-service-go

    - stage: deploy
      script: ls -lh $GOPATH/src/github.com/AwesomeTeamPlayer/users-service-go/