language: go
go: '1.9'

services:
  - docker

jobs:
  include:
    - stage: install dependencies
      script: ./install-dependencies.sh

    - stage: build and deploy
      script:
        - go build -o $HOME/app github.com/AwesomeTeamPlayer/users-service-go
        - ls -lh $HOME