language: go
go: '1.9'

services:
  - docker

install:
  - go get github.com/go-sql-driver/mysql
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/rpc
  - go get github.com/gorilla/rpc/json
  - go get github.com/streadway/amqp

script: go build github.com/AwesomeTeamPlayer/users-service-go