language: go
go: '1.9'

services:
  - docker

jobs:
  include:
    - stage: install dependencies
      script: ./install-dependencies.sh

    - stage: build
      script: go build -o app github.com/AwesomeTeamPlayer/users-service-go && ls -lh

    - stage: deploy
      script: ls -lh