language: go
go: '1.9'

services:
  - docker

jobs:
  include:
    - stage: install dependencies
      script: ./install-dependencies.sh

    - stage: build and deploy
      script:
        - go build -o app github.com/AwesomeTeamPlayer/users-service-go
        - ls -lh
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker build -t awesometeamplayer/users-service-go:master .
        - docker images
        - docker push awesometeamplayer/users-service-go:master